{% set version = "24.1.0" %}
{% set sha256 = "6f7df21c3457577491c4dd2f96515d0aa861056efa059d7829dd7a172ea47965" %}

package:
  name: structlog
  version: {{ version }}

source:
  url: https://github.com/hynek/structlog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - remove-fancy-pypi-readme.patch

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -v

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs

  run:
    - python

test:
  requires:
    - pip
    - pytest
    - pytest-asyncio >=0.17
    - freezegun >=0.2.8
    - pretend
    - simplejson
  source_files:
    - tests
  imports:
    - structlog
  commands:
    - pip check
    - pytest -v tests --asyncio-mode=auto

about:
  home: https://www.structlog.org
  license: MIT
  license_family: MIT
  summary: Structured Logging for Python
  description: |
    structlog is the production-ready logging solution for Python:
    - Simple: Everything is about functions that take and return dictionaries - all hidden behind familiar APIs.
    - Powerful: Functions and dictionaries aren't just simple but also powerful. structlog leaves you in control.
    - Fast: structlog is not hamstrung by designs of yore. Its flexibility comes not at the price of performance.
  license_file:
    - LICENSE-MIT
  dev_url: https://github.com/hynek/structlog
  doc_url: https://www.structlog.org

extra:
  recipe-maintainers:
    - vamega
    - aldanor
