{% set version = "20.1.0" %}
{% set sha256 = "5e4f4e672cd8586cfbb96a6e62cb423f563dfa98f29364a4074e2520b2f6b394" %}

package:
  name: structlog
  version: {{ version }}

source:
  fn: structlog-{{ version }}.tar.gz
  url: https://github.com/hynek/structlog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six

test:
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: MIT/Apache 2.0
  summary: Structured Logging for Python
  license_file:
    - LICENSE
    - LICENSE.apache2
    - LICENSE.mit

extra:
  recipe-maintainers:
    - vamega
    - aldanor
