{% set version = "21.4.0" %}
{% set sha256 = "ae095b06ec6a2c7cd815a36581ba065c7790ecbe04bc7bd92b14f453e7e0c39e" %}

package:
  name: structlog
  version: {{ version }}

source:
  fn: structlog-{{ version }}.tar.gz
  url: https://github.com/hynek/structlog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - flit

  run:
    - python >=3.6
    - six

test:
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE
    - LICENSE.apache2
    - LICENSE.mit

extra:
  recipe-maintainers:
    - vamega
    - aldanor
