{% set version = "21.2.0" %}
{% set sha256 = "23b3bf23bfd3f70b88b23698e43b826787dd25bd4b17cb61e15e643deb2a895e" %}

package:
  name: structlog
  version: {{ version }}

source:
  fn: structlog-{{ version }}.tar.gz
  url: https://github.com/hynek/structlog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - six

test:
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE
    - LICENSE.apache2
    - LICENSE.mit

extra:
  recipe-maintainers:
    - vamega
    - aldanor
