{% set version = "24.1.0" %}
{% set sha256 = "6f7df21c3457577491c4dd2f96515d0aa861056efa059d7829dd7a172ea47965" %}

package:
  name: structlog
  version: {{ version }}

source:
  url: https://github.com/hynek/structlog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - remove-fancy-pypi-readme.patch

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -v

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs

  run:
    - python

test:
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: Apache-2.0 OR MIT
  summary: Structured Logging for Python
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - vamega
    - aldanor
