{% set name = "structlog" %}
{% set version = "25.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hynek/structlog/archive/refs/tags/{{ version }}.tar.gz
  sha256: ca447e91f03a18b3ae1f1917342c023091e923418409e19cfe67b90dbdce2694

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -v

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-fancy-pypi-readme >=22.8.0
    - hatch-vcs
  run:
    - python
    - typing-extensions  # [py<311]

test:
  requires:
    - pip
    - pytest >=6.0
    - simplejson
    - pytest-asyncio >=0.17
    - time-machine>=2.14.1
  source_files:
    - tests
    - pyproject.toml
  imports:
    - structlog
  commands:
    - pip check
    # check that pip gets the correct version
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://www.structlog.org
  license: Apache-2.0 OR MIT
  license_family: OTHER
  summary: Structured Logging for Python
  description: |
    structlog is the production-ready logging solution for Python:
    - Simple: Everything is about functions that take and return dictionaries - all hidden behind familiar APIs.
    - Powerful: Functions and dictionaries aren't just simple but also powerful. structlog leaves you in control.
    - Fast: structlog is not hamstrung by designs of yore. Its flexibility comes not at the price of performance.
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - COPYRIGHT
  dev_url: https://github.com/hynek/structlog
  doc_url: https://www.structlog.org

extra:
  recipe-maintainers:
    - vamega
    - aldanor
