{% set version = "24.4.0" %}
{% set sha256 = "d85aa814a735cf7d7c4a36ea3052d35ca7b2c631251f20950b1c17eacf1f4651" %}

package:
  name: structlog
  version: {{ version }}

source:
  url: https://github.com/hynek/structlog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -v

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-fancy-pypi-readme >=22.8.0
    - hatch-vcs
  run:
    - python

test:
  requires:
    - pip
    - pytest >=6.0
    - freezegun >=0.2.8
    - pretend
    - python-rapidjson  # [not s390x]
    - pytest-asyncio >=0.17
  source_files:
    - tests
  imports:
    - structlog
  commands:
    - pip check
    - pytest -v tests --ignore=tests/test_twisted.py -k "not test_delattr_missing"

about:
  home: https://www.structlog.org
  license: Apache-2.0 OR MIT
  license_family: OTHER
  summary: Structured Logging for Python
  description: |
    structlog is the production-ready logging solution for Python:
    - Simple: Everything is about functions that take and return dictionaries - all hidden behind familiar APIs.
    - Powerful: Functions and dictionaries aren't just simple but also powerful. structlog leaves you in control.
    - Fast: structlog is not hamstrung by designs of yore. Its flexibility comes not at the price of performance.
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - COPYRIGHT
  dev_url: https://github.com/hynek/structlog
  doc_url: https://www.structlog.org

extra:
  recipe-maintainers:
    - vamega
    - aldanor
