{% set version = "18.2.0" %}
{% set sha256 = "0455e1304f963ac3e7985f79263a0315b95c3ba28db23b57c7ac97a3cfdf204f" %}

package:
  name: structlog
  version: {{ version }}

source:
  fn: structlog-{{ version }}.tar.gz
  url: https://github.com/hynek/structlog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - structlog

about:
  home: http://www.structlog.org
  license: MIT/Apache 2.0
  summary: Structured Logging for Python

extra:
  recipe-maintainers:
    - vamega
    - aldanor
