{% set name = "structlog" %}
{% set version = "26.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hynek/structlog/archive/refs/tags/{{ version }}.tar.gz
  sha256: a32b711804f80404b1c6de47556df2215c399acec2d38199e91ceb4a2ca1fd51

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -v

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-fancy-pypi-readme >=22.8.0
    - hatch-vcs
  run:
    - python
    - typing-extensions  # [py<311]
    - typing_extensions  # [py<311]

test:
  requires:
    - pip
    - pytest >=6.0
    - simplejson
    - pytest-asyncio >=0.17
    - time-machine>=2.14.1
  source_files:
    - tests
    - pyproject.toml
  imports:
    - structlog
  commands:
    - pip check
    # check that pip gets the correct version
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://www.structlog.org
  license: Apache-2.0 OR MIT
  license_family: OTHER
  summary: Structured Logging for Python
  description: |
    structlog is the production-ready logging solution for Python:
    - Simple: Everything is about functions that take and return dictionaries - all hidden behind familiar APIs.
    - Powerful: Functions and dictionaries aren't just simple but also powerful. structlog leaves you in control.
    - Fast: structlog is not hamstrung by designs of yore. Its flexibility comes not at the price of performance.
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - COPYRIGHT
  dev_url: https://github.com/hynek/structlog
  doc_url: https://www.structlog.org

extra:
  recipe-maintainers:
    - vamega
    - aldanor
