travis:
  secure:
    BINSTAR_TOKEN: oBGCZXK1UoSaG7QeP1oAGZjBvBmVbxThQf9tf4fkvIomRVn/06qwWVUBUB37ynTT+fSnnJEVCmlt0Fo/MagsUtYT91mF+o7rNaRc5PRtejtj0gYX4O+OGG+N0tdZtimKz1k9XvrM3T2hkFQJAxvpyerjZfPQDB3VFT2tshBo7QV3s45D8GMiZFFe0SV5XTrVOvDGV3HsherAMo+Le/clSQoXIGZfZUhei04YQH/irPIWp9k2CPidAzI6me8MndlqWVbFPHIj8a97YGeWSLLX7E1bi7H+NYx/vbtyKU2jPGKVnG2F85JRQBHg6orH3GOIFG8I/arzdT69FXYRanQ5G9zgxQCPf3xZil/fExc+WnmzhrJc5UocvU+PhFZRVBxuPlU2DgQXSLvLwbwrwqJ7mQ9gc57cGjz3Ah80HQletr+kJ9Pm1MGl36K9hbMoXLxrJ+yWZU77x2iimqHmwUaosBSpZXxQ6Y8Xp6tZa3PUGk/uNGtLEGgFr87wLmf3B3EWa6wS0MpBg+sKUaCIGQyLOR72Qi1igi96ZTgVs+ui1TbUlfS08n+HqCr+YMncO1FyQXAL7VbkEs0B0tft5jn2PUdpkB6vUUU4xCjNuk0cRic/TpU7z7rh6Yf+tRaufN2eD12zuEX61yz3HOKkEJB4R9DJ8hCRORM47xZDJteDWCw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
