travis:
  secure:
    BINSTAR_TOKEN: Uq1QS+gsgTR1ap93NjSHJhZsupcS5lOY/S/y49C1qNqJcE+2eb3ehIfOe4eOrV+ZAkDQ2yPXzUhSKB0/4Otg0f0FQQ816aeo7BgP0y++yJkpVkS2PTX0Ge0HXgzOKW5qrYUzLX7GJgaeYna4Se4VisRSPnhgVHZGlKm/AlNIkmLQdNofwkuF1BOxdEegAuzVh/JTrTecXVAeHgIAK/N+XqA17f0fIpzQ63N5K7UQwngFCilbWuulCql6NmweDnXxHMgk2/VRj8w848bhw2xM8oLZu7q8FZssAq3M3mDIl4vL2Qe78OehDusoGl1AKdSugyStjY3UxuWlTWeNoV02zihtRZhwx6zp3DIA0wNQWYWWh1lQfsNymfZph5dV+OjbWdYhmPelJYXoE9Ob1HDShl+1cJbD4Cyob4EfeltjKYQGcv7d+BAh6OZx2dEJOM7le6r2SrZmfH5zpillzl0wvYkM+DuAYzLJT2lM85LrBOO+1YFsgqNw0fqE4Fvz4mU/iWrNLrGzn8kU/MrYnwNE5yVdIzOmz1hg71Vf7h1Rk10cU7B3ON+wc29NTisA4dGbQMA1DrlK46rK9md8Wx8lN+sdjXyfY64TFL6PxtnwuNujBle5sFFIrWUKiPg/MArPwWQZmM68tVV3YK0FJG4ojJhYpSk1ltKgGwX5dNBBc+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
